apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- svc.yaml
- ingress.yaml
images:
- name: quarkus-demo
  newName: twintpocregistry.azurecr.io/quarkus-poc
  newTag: "8"
